# Generated by Django 5.2.5 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_is_user_chatmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotfaq',
            name='role_scope',
            field=models.CharField(
                choices=[
                    ('ALL', 'All Roles'),
                    ('USER', 'User'),
                    ('STUDIO', 'Studio'),
                    ('ADMIN', 'Admin'),
                ],
                default='ALL',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='policy_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='role_at_message_time',
            field=models.CharField(
                choices=[
                    ('USER', 'User'),
                    ('STUDIO', 'Studio'),
                    ('ADMIN', 'Admin'),
                    ('UNKNOWN', 'Unknown'),
                ],
                default='UNKNOWN',
                max_length=10,
            ),
        ),
    ]
