# Generated by Django 5.2.5 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_role_scoping_and_policy_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response_mode',
            field=models.CharField(
                choices=[
                    ('legacy', 'Legacy'),
                    ('intent_answer', 'Intent Answer'),
                    ('faq_hit', 'FAQ Hit'),
                    ('fallback', 'Fallback'),
                    ('guardrail', 'Guardrail'),
                    ('admin_safe', 'Admin Safe'),
                    ('standard', 'Standard'),
                ],
                default='legacy',
                max_length=20,
            ),
        ),
    ]
