# Generated by Django 5.2.5 on 2026-03-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_remove_portfolio_studio_remove_review_studio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('portfolio_visibility', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('device_login_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studio Preference',
                'verbose_name_plural': 'Studio Preferences',
            },
        ),
    ]
