# Generated by Django 5.2.5 on 2026-03-07 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Studio', 'verbose_name_plural': 'Studios'},
        ),
        migrations.AddField(
            model_name='studio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='studio',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display on homepage'),
        ),
        migrations.AddField(
            model_name='studio',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Studio has been verified'),
        ),
        migrations.AddField(
            model_name='studio',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='price_range',
            field=models.CharField(blank=True, help_text='e.g., $100-$500 per hour', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='specializations',
            field=models.TextField(blank=True, help_text='Comma-separated specializations', null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='studio',
            index=models.Index(fields=['-is_featured', '-created_at'], name='studios_stu_is_feat_249587_idx'),
        ),
        migrations.AddIndex(
            model_name='studio',
            index=models.Index(fields=['location'], name='studios_stu_locatio_0fb09c_idx'),
        ),
    ]
