# Generated by Django 5.2.5 on 2026-03-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_alter_studio_options_studio_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
