# Generated by Django 5.2.5 on 2026-03-31 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('studios', '0006_studio_price_per_hour_studio_rating_studioimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='studios.service'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='time_slot',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
